### ISSUE TITLE
User Nav

### ISSUE THREAD

**Issue by alvaroormeno** [BMArsenault/proj-02#5]
### Tasks
- [x] View
  - [x] Sign up 
  - [x] Sign in
  - [x] Sign out
  
- [x] Routes/controller 
  - [ ] /API /Sign Up
  - [ ] /API /Log in
  - [ ] /API / Logout 

- [x] Models / Database / User table
  - [ ]  Use table 
  - [ ]  Email field
  - [ ]  Name field
  

![Screen Shot 2022-01-12 at 7 56 36 PM](https://user-images.githubusercontent.com/56319897/149246911-5038453b-d8da-4a4a-8497-904ad7124a36.png)
